---
title: "Hotel_exploration"
author: "Alan"
date: "2024-10-19"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(brms)
library(ggplot2)
library(lme4)
library(lubridate)
library(stringr)
library(cowplot)

```

## R Markdown


```{r cars}
Hotel_Reviews <- readr::read_csv("Data/Hotel_Reviews.csv", quote =",")


countries <- readr::read_csv("Data/countries.csv", quote ="\"")

Hotel_Reviews$Country = NA
for (i in countries$name){
  Hotel_Reviews$Country[str_detect(Hotel_Reviews$Hotel_Address, i)] = i
  }
  

summary(Hotel_Reviews)

Hotel_Reviews <- Hotel_Reviews %>% mutate(time = as.numeric(as.POSIXct(Review_Date,format="%m/%d/%Y") ))
date_object <- as.Date(Hotel_Reviews$Review_Date, format = "%m/%d/%Y")
months <- month(date_object)
Hotel_Reviews$date_object = date_object
Hotel_Reviews$month = months
Hotel_Reviews$num_date_object = as.numeric(date_object)/365





# Filter hotels with at least 500 reviews
Hotel_Reviews <- Hotel_Reviews %>%
  group_by(Hotel_Name) %>%
  filter(n() >= 500) %>%
  ungroup()


avg = Hotel_Reviews %>% group_by(Hotel_Name) %>% summarise(Avg = mean(Average_Score),
                                                    own_avg = mean(Reviewer_Score))

head(avg)

```


```{r}
# Plot predictions over time with confidence intervals
 p_time = ggplot(Hotel_Reviews, aes(x = date_object, y = Reviewer_Score, color = Country)) +
   geom_point(alpha=0.02) +
  geom_smooth() +
   labs(title = "Reviewer Scores Over Time ",
        x = "Date",
        y = "Reviewer Score") +
      coord_cartesian(ylim = c(6, 10)) + 
   theme_minimal() + theme(legend.position = "top")

 p_month = ggplot(Hotel_Reviews, aes(x = month, y = Reviewer_Score, color = Country)) +
   geom_point(alpha=0.02) +
  geom_smooth() +
   labs(title = "Reviewer Scores Over The Year ",
        x = "Months",
        y = "Reviewer Score") +
      coord_cartesian(ylim = c(6, 10)) + 
   theme_minimal() + theme(legend.position = "top")

 
plot_grid(p_time,p_month)

```

```{r}

 new_data <- Hotel_Reviews %>%
   dplyr::select(Country, month, date_object,Hotel_Name,Reviewer_Score,Average_Score) %>% filter(Hotel_Name %in% sample(unique(Hotel_Reviews$Hotel_Name),5))

 ggplot(new_data, aes(x = date_object, y = Reviewer_Score, color = Hotel_Name)) +
   geom_point(alpha=0.02) +
  geom_smooth() +
  geom_line(aes(y=Average_Score)) +
   labs(title = "Reviewer Scores Over Time ",
        x = "Date",
        y = "Reviewer Score") +
      coord_cartesian(ylim = c(5, 10)) + 
   theme_minimal() + theme(legend.position = "top")



```


```{r}




trip_time = 31 #day 
trip_start = max(Hotel_Reviews$date_object)-trip_time 
booking_time = trip_start
attention_window = 356


Hotel_Reviews = Hotel_Reviews %>% mutate(time_ref = as.numeric(date_object- booking_time))

detection_data = Hotel_Reviews %>% filter(date_object < booking_time &
                                            date_object > (booking_time-attention_window) )


test_data = Hotel_Reviews %>% filter(date_object > trip_start &
                                            date_object < (trip_start+trip_time) )





```






```{r pressure}


prior <- c(
  prior("normal(10, 2)", class = "Intercept"),
  set_prior("normal(0, 0.1)", class = "sd")
)

 fit = brm(bf(
   Reviewer_Score ~ 1 +  (1 + time_ref || Hotel_Name)),
   data = detection_data, cores = 4, chains = 4,  backend = "cmdstanr", threads = threading(4), prior = prior)
 
 
 
 
 

```

```{r}

 
random_effct = ranef(fit,probs = c(0.1, 0.9))$Hotel_Name[,,1] #Intercept
 random_effct = data.frame(random_effct) %>% mutate(Name= rownames(.)) %>%   arrange(Estimate) %>%
  mutate(Name = factor(Name, levels = Name)) %>% mutate(Pos = ifelse(Q10>0, 1, 0),
                                                        Neg = ifelse(Q90<0, 1, 0),) 
 
 
 random_effct %>% ggplot(aes(x=Name, y= Estimate)) + geom_point() +
   geom_pointrange(aes(ymin = Q10 ,ymax=Q90)) + coord_flip() + geom_hline(yintercept = 0)
 
 
random_effct2 = ranef(fit,probs = c(0.1, 0.9))$Hotel_Name[,,2] #Slope
 random_effct2 = data.frame(random_effct2) %>% mutate(Name= rownames(.)) %>%   arrange(Estimate) %>%
  mutate(Name = factor(Name, levels = Name)) %>% mutate(Pos = ifelse(Q10>0, 1, 0),
                                                        Neg = ifelse(Q90<0, 1, 0),) 
 
 
 random_effct2 %>% ggplot(aes(x=Name, y= Estimate, colour = as.factor(Neg))) + geom_point() +
   geom_pointrange(aes(ymin = Q10 ,ymax=Q90)) + coord_flip() + geom_hline(yintercept = 0)
 
 mean(random_effct2$Neg)
 
 
```
```{r}

# Extract coefficients

prediction = predict(fit, newdata = detection_data %>% mutate(time_ref = as.numeric(time_ref)), cores = 4)



detection_data2 = cbind(detection_data,prediction)
rmse = sqrt(mean((detection_data2$Estimate - detection_data$Reviewer_Score)^2))
ame = (mean(abs(detection_data2$Estimate - detection_data$Reviewer_Score)))
cat(paste0("Insample:\nAbsolute error: ", ame,
             "\nRMSE: ",rmse))
 
 
prediction = predict(fit, newdata = test_data %>% mutate(time_ref = as.numeric(time_ref)), cores = 4)
test_data2 = cbind(test_data,prediction)

rmse = sqrt(mean((test_data2$Estimate - test_data$Reviewer_Score)^2))
ame = (mean(abs(test_data2$Estimate - test_data$Reviewer_Score)))
rmse_ho = sqrt(mean((test_data$Average_Score - test_data$Reviewer_Score)^2))
ame_ho = (mean(abs(test_data$Average_Score - test_data$Reviewer_Score)))
cat(paste0("\nPrediction:\nAbsolute error: ", ame, " vs. H0- ",ame_ho,
             "\nRMSE: ",rmse, "vs. H0- ",rmse_ho))
```
```{r}


grouped_test_data <- test_data2 %>% group_by(Hotel_Name) %>% summarise(mean_review = mean(Reviewer_Score), Average_Score =mean(Average_Score)) %>%
  left_join(random_effct2 %>% mutate(Hotel_Name=Name), by = "Hotel_Name") %>% mutate(correct_neg = (sign(Average_Score-mean_review)==Neg), correct_pos = (sign(mean_review-Average_Score)==Pos)  )

grouped_test_data %>% group_by(Neg) %>% summarise(m = mean(correct_neg))
grouped_test_data %>% group_by(Pos) %>% summarise(m = mean(correct_pos))


```



```{r}
#errors = detection_data %>% group_by(Hotel_Name) %>% summarise(h0_error = mean(Reviewer_Score-Average_Score), model_error = mean(Reviewer_Score-pred))


test_window = expand.grid(Hotel_Name = unique(test_data$Hotel_Name), time_ref = seq(-360, max(test_data$time_ref),7), Reviewer_Score2 =NA)
#detection_data2 = detection_data2 %>% mutate(Estimate = NA)
detection_data2 = detection_data2 %>% mutate(Reviewer_Score2 = Reviewer_Score)
prediction = predict(fit, newdata = test_window, cores = 4)



test_window = cbind(test_window,prediction)

plot_data = detection_data2

library(shiny)
library(DT)

hotel_names <- unique(plot_data$Hotel_Name)

# Define UI
ui <- fluidPage(
  mainPanel(
    selectInput("hotel", "Select Hotel:", choices = hotel_names),
    plotOutput("distPlot")
  )
)

# Define server logic
server <- function(input, output) {
  output$distPlot <- renderPlot({
    
    selected_hotel <- input$hotel
    
    # Filter data for the selected hotel
    filtered_data <- plot_data %>% filter(Hotel_Name == selected_hotel)
    
    
    # Check if the selected hotel has Neg == TRUE
    neg_hotel <- random_effct2 %>% filter(Name == selected_hotel & Neg == TRUE)

    
    # Plot
   p =  ggplot(filtered_data, aes(x = time_ref, y = Reviewer_Score2)) +
      geom_line(aes(y = Average_Score), color = "gray") +
      geom_point(aes(x = time_ref, y = Reviewer_Score2), alpha = 0.5) +
      geom_smooth(aes(x = time_ref, y = Reviewer_Score2), lty = "dashed", span = 1) +
      geom_line(data= test_window  %>% filter(Hotel_Name == selected_hotel), aes(x=time_ref, y=Estimate)) +
      labs(title = "Predicted Reviewer Scores Over Time",
           x = "Date",
           y = "Predicted Reviewer Score") +
      coord_cartesian(ylim = c(6, 10)) + 
      theme_minimal() + 
      theme(legend.position = c(0.5, 0.9))
   if(random_effct2$Neg[random_effct2$Name == selected_hotel]==1)p =  p + geom_text(data = neg_hotel, aes(x = max(filtered_data$time_ref), y = 9, label = "!"), size = 10, color = "red", vjust = -1)
   if(random_effct2$Pos[random_effct2$Name == selected_hotel] ==1) p =  p + geom_text(data = neg_hotel, aes(x = max(filtered_data$time_ref), y = 9, label = "+"), size = 10, color = "green", vjust = -1)
   p
  })
}



shinyApp(ui = ui, server = server)

```

# Bayesian



```{r}

random_effects <- ranef(fit)
random_effects_df <- as.data.frame(random_effects$Hotel_Name)
random_effects_df$Hotel_Name <- rownames(random_effects$Hotel_Name)

# Extract standard deviations
std_devs <- as.data.frame(VarCorr(fit)$Hotel_Name)
# Reorder by random slopes
random_effects_df = random_effects_df[order(random_effects_df$date_object),] 

ggplot(random_effects_df, aes(x = Hotel_Name)) +
  geom_point(aes(y = date_object), color = "red") +
  geom_errorbar(aes(ymin = date_object - 1.96 * 0.0000496, 
                    ymax = date_object + 1.96 * 0.0000496), 
                width = 0.2, color = "red") +
  labs(title = "Random Effects for Hotels",
       x = "Hotel Name",
       y = "Random Effects") 
```
# Deteroation detection

```{r}
library(tidyr)
target =  test_data %>% select(Average_Score, Hotel_Name, Reviewer_Score)

features = detection_data %>% select(Hotel_Name,Reviewer_Score) %>% pivot_wider(names_from= Hotel_Name, values_from = Reviewer_Score)

data = test_data

# Load necessary libraries
library(caret)
library(dplyr)

# Sample data
# Assume 'data' is your dataframe with columns: 'Reviewer_Score', 'time', 'Hotel_Name'
# data <- read.csv("your_data.csv")

# Calculate past average Reviewer_Score for each hotel
data <- data %>%
  arrange(Hotel_Name, time) %>%
  group_by(Hotel_Name) %>%
  mutate(past_avg_Reviewer_Score = cummean(lag(Reviewer_Score, default = first(Reviewer_Score))))

# Create a binary target variable: 1 if Reviewer_Score is more than 1 point lower than past average
data <- data %>%
  mutate(target = ifelse(Reviewer_Score < past_avg_Reviewer_Score - 1, 1, 0))

# Split the data into training and testing sets
set.seed(123)
trainIndex <- createDataPartition(data$target, p = .8, 
                                  list = FALSE, 
                                  times = 1)
trainData <- data[trainIndex,]
testData <- data[-trainIndex,]

# Train a logistic regression model
model <- train(target ~  past_avg_Reviewer_Score, data = trainData, method = "glm", family = "binomial")

# Make predictions
predictions <- as.numeric(predict(model, newdata = testData))

# Evaluate the model
confusionMatrix(as.factor(round(predictions)), as.factor(testData$target))
```
# DLM approach

```{r}

library(dlm)


buildModel <- function(parm) {
  dlmModPoly(order = 2, dV = exp(parm[1]), dW = exp(parm[2:3]))
}


fit <- dlmMLE(detection_data$Reviewer_Score, parm = c(0, 0,0), build = buildModel)

model <- buildModel(fit$par)

filtered <- dlmFilter(detection_data$Reviewer_Score, model)
smoothed <- dlmSmooth(filtered)


#cbind(detection_data,s=dropFirst(smoothed$s)) %>% ggplot(aes(x=date_object, y = Reviewer_Score)) + geom_point() +geom_smooth() +
#  geom_point(aes(x=date_object, y = s), color="red")


```


```{r}
errors = detection_data %>% group_by(Hotel_Name) %>% summarise(h0_error = mean(Reviewer_Score-Average_Score), model_error = mean(Reviewer_Score-pred))


test_data = test_data %>% mutate(Reviewer_Score2 = NA)
detection_data = detection_data %>% mutate(Reviewer_Score2 = Reviewer_Score)

plot_data = cbind(detection_data,s=dropFirst(smoothed$s[,2])) 
#plot_data = cbind(detection_data,s=(filtered$y)) 

library(shiny)
library(DT)

hotel_names <- unique(plot_data$Hotel_Name)

# Define UI
ui <- fluidPage(
  mainPanel(
    selectInput("hotel", "Select Hotel:", choices = hotel_names),
    plotOutput("distPlot")
  )
)

# Define server logic
server <- function(input, output) {
  output$distPlot <- renderPlot({
    selected_hotel <- input$hotel
    
    # Filter data for the selected hotel
    filtered_data <- plot_data %>% filter(Hotel_Name == selected_hotel)
    
    
    # Plot
    ggplot(filtered_data, aes(x = date_object, y = s, color = Hotel_Name)) +
      geom_line() +
      geom_line(aes(y = Average_Score), color = "gray") +
      geom_point(aes(x = date_object, y = Reviewer_Score2), alpha = 0.5) +
      geom_smooth(aes(x = date_object, y = Reviewer_Score2), lty = "dashed") +
      labs(title = "Predicted Reviewer Scores Over Time",
           x = "Date",
           y = "Predicted Reviewer Score") +
      ylim(6, 10) +
      theme_minimal() + 
      theme(legend.position = c(0.5, 0.9))
  })
}



shinyApp(ui = ui, server = server)

```





# Hierachical versus fixed effect

Non hierarchical takes for ever and is not better
```{r pressure}

 
 fit = lm(
   Reviewer_Score ~ 0 + date_object * Hotel_Name,
   data = detection_data)
 

 detection_data = detection_data %>% mutate(pred = predict(fit, newdata = .))
rmse = sqrt(mean((detection_data$pred - detection_data$Reviewer_Score)^2))
ame = (mean(abs(detection_data$pred - detection_data$Reviewer_Score)))
cat(paste0("Insample:\nAbsolute error: ", ame,
             "\nRMSE: ",rmse))
 
 
test_data = test_data %>% mutate(pred = predict(fit, newdata = .))
rmse = sqrt(mean((test_data$pred - test_data$Reviewer_Score)^2))
ame = (mean(abs(test_data$pred - test_data$Reviewer_Score)))
cat(paste0("\nPrediction:\nAbsolute error: ", ame,
             "\nRMSE: ",rmse))

```




