---
title: "Hotel_exploration"
author: "Alan"
date: "2024-10-19"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(brms)
library(ggplot2)
library(lme4)
library(lubridate)
library(stringr)
library(cowplot)
library(shiny)
```

## R Markdown


```{r cars}
shiny_t = F #load shiny stuff?
source("functions.R")

Hotel_Reviews <- data_loader()


# Filter hotels with at least 500 reviews
Hotel_Reviews <- Hotel_Reviews %>%
  group_by(Hotel_Name) %>%
  filter(n() >= 200) %>% #, Country=="United Kingdom"
  ungroup()
min_number=200


t_threshold_slope =  qt(0.8,Inf)
t_threshold =  qt(0.9,Inf) #not used


```
Base data
```{r}
dim(Hotel_Reviews)
length(unique(Hotel_Reviews$Hotel_Name))
```



```{r}
trip_time = 356/2 #day 
trip_start = max(Hotel_Reviews$date_object)-trip_time 
booking_time = trip_start
attention_window = 356*2 


my_data = Hotel_Reviews %>%
  filter(date_object > (booking_time - attention_window))


my_data <- my_data %>%
  mutate(group = factor(ifelse(date_object < booking_time, "before", "after"), levels=c("before", "after"))) 


keep_Hotels = my_data %>% group_by(group,Hotel_Name) %>% tally() %>%
  filter(n >= min_number) 

Hotel_Reviews = Hotel_Reviews %>% mutate(time_ref = as.numeric(date_object- booking_time)/30.5) %>%
  filter(Hotel_Name %in% keep_Hotels$Hotel_Name)

my_data %>%
  filter(Hotel_Name %in% keep_Hotels$Hotel_Name)


train_data = Hotel_Reviews %>% filter(date_object < booking_time &
                                            date_object > (booking_time-attention_window) )


test_data = Hotel_Reviews %>% filter(date_object > trip_start &
                                            date_object < (trip_start+trip_time) )


```



```{r}

calc_dprime = function(Predicted, Actual){
  
  
confusion_matrix <- table(Predicted = Predicted, Actual = Actual)
hit_rate <- confusion_matrix[2, 2] / sum(confusion_matrix[, 2])  # True Positives / (True Positives + False Negatives)
false_alarm_rate <- confusion_matrix[2, 1] / sum(confusion_matrix[, 1])  # False Positives / (False Positives + True Negatives)


# Adjust rates if they are 0 or 1
hit_rate <- ifelse(hit_rate == 1, 0.99, ifelse(hit_rate == 0, 0.01, hit_rate))
false_alarm_rate <- ifelse(false_alarm_rate == 1, 0.99, ifelse(false_alarm_rate == 0, 0.01, false_alarm_rate))

# Calculate d'
d_prime <- qnorm(hit_rate) - qnorm(false_alarm_rate)
return(d_prime)
  }

trans_slope = function(t_threshold,fit){
  
  all_coefficients = coef(fit)
model_summary <- summary(fit)
 t_threshold =  qt(t_threshold,Inf)



# Extract the coefficients table
coefficients_table <- model_summary$coefficients

# Extract only the interaction terms
interaction_summary <- coefficients_table[grep(":", rownames(coefficients_table)), ]


 time_effct = data.frame(interaction_summary) %>% mutate(Name= rownames(.),
                                                         Name = stringr::str_replace(Name, c("Hotel_Name"),""),
                                                         Name = stringr::str_replace(Name, c(":time_ref"),"")) %>%
   arrange(Estimate) %>%
  mutate(Name = factor(Name, levels = Name)) %>% mutate(Pos = ifelse(t.value>t_threshold, 1, 0),
                                                        Neg = ifelse(t.value<(-t_threshold), 1, 0),
                                                        tendency = Pos-Neg)
 return(time_effct)
 
}
trans_dif = function(t_threshold){

all_coefficients = coef(fit_dif)
model_summary <- summary(fit_dif)

t_threshold =  qt(t_threshold,Inf)



# Extract the coefficients table
coefficients_table <- model_summary$coefficients

# Extract only the interaction terms
interaction_summary <- coefficients_table[grep(":", rownames(coefficients_table)), ]


 time_effct2 = data.frame(interaction_summary) %>% mutate(Name= rownames(.),
                                                         Name = stringr::str_replace(Name, c("Hotel_Name"),""),
                                                         Name = stringr::str_replace(Name, c(":groupafter"),"")) %>%
   arrange(Estimate) %>%
  mutate(Name = factor(Name, levels = Name)) %>% mutate(Pos = ifelse(t.value>t_threshold, 1, 0),
                                                        Neg = ifelse(t.value<(-t_threshold), 1, 0),
                                                        tendency = Pos-Neg)
 return(time_effct2)

}
```



```{r}



fit_dif = lm(
   Reviewer_Score ~ 0 +  Hotel_Name * group:Hotel_Name, data = my_data)

```



```{r pressure}

all_coefficients = coef(fit_dif)
model_summary <- summary(fit_dif)
#fit = strip_lm(fit)





# Extract the coefficients table
coefficients_table <- model_summary$coefficients

# Extract only the interaction terms
interaction_summary <- coefficients_table[grep(":", rownames(coefficients_table)), ]


 time_effct2 = data.frame(interaction_summary) %>% mutate(Name= rownames(.),
                                                         Name = stringr::str_replace(Name, c("Hotel_Name"),""),
                                                         Name = stringr::str_replace(Name, c(":groupafter"),"")) %>%
   arrange(Estimate) %>%
  mutate(Name = factor(Name, levels = Name)) %>% mutate(Pos = ifelse(t.value>t_threshold & abs(Estimate)>0.1, 1, 0),
                                                        Neg = ifelse(t.value<(-t_threshold) & abs(Estimate)>0.1, 1, 0),
                                                        tendency = Pos-Neg) 
 time_effct2 = data.frame(interaction_summary) %>% mutate(Name= rownames(.),
                                                         Name = stringr::str_replace(Name, c("Hotel_Name"),""),
                                                         Name = stringr::str_replace(Name, c(":groupafter"),"")) %>%
   arrange(Estimate) %>%
  mutate(Name = factor(Name, levels = Name)) %>% mutate(Pos = ifelse(Estimate>0.2, 1, 0),
                                                        Neg = ifelse(Estimate< (-0.2), 1, 0),
                                                        tendency = Pos-Neg) 
 
 time_effct2 %>% ggplot(aes(x=Name, y= Estimate, colour = as.factor(tendency))) + geom_point() +
   geom_pointrange(aes(ymin = Estimate - (Std..Error*2) ,ymax= Estimate + (Std..Error*2)),alpha=0.2) + 
   coord_flip() + geom_hline(yintercept = 0) + theme(legend.position = "None") +
   scale_color_manual(values=c("#F8766D", "#56B4E9", "#7CAE00")) + 
  annotate("text", x = Inf, y = Inf, label = paste("Positive trend:", round(mean(time_effct2$Pos), 2)), hjust = 1, vjust = 2+3, size = 4, color = "#7CAE00") +
  annotate("text", x = Inf, y = Inf, label = paste("No clear trend:", round(mean(time_effct2$tendency==0), 2)), hjust = 1, vjust = 3.5+3, size = 4, color = "#56B4E9") +
  annotate("text", x = Inf, y = Inf, label = paste("Negative trend:", round(mean(time_effct2$Neg), 2)), hjust = 1, vjust = 5+3, size = 4, color = "#F8766D") 

 
max(time_effct2$Estimate[time_effct2$Neg==1])

```



```{r pressure}
fit_slope = lm(
   Reviewer_Score ~ 0 +  Hotel_Name + time_ref:Hotel_Name, data = train_data)
#save(fit, file = "Simple_lm.RData")
all_coefficients = coef(fit_slope)
model_summary <- summary(fit_slope)
#fit = strip_lm(fit)

#load(file = "Simple_lm.RData")
```



```{r}



# Extract the coefficients table
coefficients_table <- model_summary$coefficients

# Extract only the interaction terms
interaction_summary <- coefficients_table[grep(":", rownames(coefficients_table)), ]


 time_effct = data.frame(interaction_summary) %>% mutate(Name= rownames(.),
                                                         Name = stringr::str_replace(Name, c("Hotel_Name"),""),
                                                         Name = stringr::str_replace(Name, c(":time_ref"),"")) %>%
   arrange(Estimate) %>%
  mutate(Name = factor(Name, levels = Name)) %>% mutate(Pos = ifelse(t.value>t_threshold_slope, 1, 0),
                                                        Neg = ifelse(t.value<(-t_threshold_slope), 1, 0),
                                                        tendency = Pos-Neg) 

 
 time_effct %>% ggplot(aes(x=Name, y= Estimate, colour = as.factor(tendency))) + 
   geom_point() +
   geom_pointrange(aes(ymin = Estimate - (Std..Error*2) ,ymax= Estimate + (Std..Error*2)),alpha=0.2) + 
   coord_flip() +
   geom_hline(yintercept = 0) + theme(legend.position = "None") +
   scale_color_manual(values=c("#F8766D", "#56B4E9", "#7CAE00")) + 
  annotate("text", x = Inf, y = Inf, label = paste("Positive trend:", round(mean(time_effct$Pos), 2)), hjust = 1, vjust = 2+3, size = 4, color = "#7CAE00") +
  annotate("text", x = Inf, y = Inf, label = paste("No clear trend:", round(mean(time_effct$tendency==0), 2)), hjust = 1, vjust = 3.5+3, size = 4, color = "#56B4E9") +
  annotate("text", x = Inf, y = Inf, label = paste("Negative trend:", round(mean(time_effct$Neg), 2)), hjust = 1, vjust = 5+3, size = 4, color = "#F8766D") + ylim(-1,1.1)
```




```{r}
time_effct2$Neg_label=time_effct2$Neg
time_effct2$Pos_label=time_effct2$Pos
time_effct2$tendency_label=time_effct2$tendency
both = merge(time_effct, time_effct2 %>% select(Neg_label,Pos_label,tendency_label,Name, Estimate ), by ="Name")
m_my_data = my_data %>% group_by(Hotel_Name, group) %>% summarise(m = mean(Reviewer_Score)) %>% group_by(Hotel_Name) %>% summarise(dif = m[group == "after"] - m[group=="before"]) %>% mutate(Name = Hotel_Name)

both = merge(both, m_my_data %>% select(Name,dif ), by ="Name") %>% filter(abs(Estimate.x)<0.5,abs(Estimate.y)<0.5)


library(caret)

confusionMatrix_h <- confusionMatrix(as.factor(rbinom(length(both$Name),1,mean(both$Neg_label))), as.factor(both$Neg_label))
predicted = as.factor(both$Neg)
actual =  as.factor(both$Neg_label)

confusionMatrix <- confusionMatrix(predicted,actual, positive = "1")
f1_score <- confusionMatrix$byClass["F1"]

print(paste0("Correlation: ",cor(both$Estimate.x,both$Estimate.y)))
print(paste0("F1: ",f1_score))
print(paste0("Kappa: ",confusionMatrix$overall["Kappa"]))
print(paste0("Sensitivity: ", confusionMatrix$byClass["Sensitivity"]))
print(paste0("Specificity: ", confusionMatrix$byClass["Specificity"]))
print(paste0("D': ",calc_dprime(predicted,actual)))
#print(paste0("D' H0: ",calc_dprime(as.factor(rbinom(length(both$Name),1,mean(both$Pos_label))),actual)))
print(paste0("RD: ",mean(both$Pos_label[both$Neg==1])/mean(both$Neg_label)))
      


```









```{r}

hit = NULL

threshold_slope = seq(0.7,0.99,0.02)
threshold_dif = seq(0.6,0.99,0.02)
grid = expand.grid(threshold_dif,threshold_slope, F1 = NA, Kappa =  NA, sensitivity = NA, Specificity=NA)

for (i in 1:length(grid[,1])){

  time_effct2 = trans_dif(grid[i,1])
  time_effct = trans_slope(grid[i,2],fit_slope)
  
time_effct2$Neg_label=time_effct2$Neg
time_effct2$Pos_label=time_effct2$Pos
time_effct2$tendency_label=time_effct2$tendency
both2 = merge(time_effct, time_effct2 %>% select(Neg_label,Pos_label,tendency_label,Name, Estimate ), by ="Name")
#grid[i,3] = mean(mean(both$Pos == 1 & both$Pos_label==1)) 
#grid[i,4] = mean(mean(both$Pos==0 & both$Pos_label == 1)) 


confusionMatrix <- confusionMatrix(as.factor(both2$Neg), as.factor(both2$Neg_label), positive = "1")
f1_score <- confusionMatrix$byClass["F1"]
grid[i,3] = f1_score
grid[i,4] = confusionMatrix$overall["Kappa"]
#grid[i,5] = confusionMatrix$byClass["Sensitivity"]
#grid[i,6] = confusionMatrix$byClass["Specificity"]
confusion_matrix <- table(Predicted = as.factor(both2$Neg), Actual = as.factor(both2$Neg_label))
hit_rate <- confusion_matrix[2, 2] / sum(confusion_matrix[, 2])  # True Positives / (True Positives + False Negatives)
false_alarm_rate <- confusion_matrix[2, 1] / sum(confusion_matrix[, 1])  # False Positives / (False Positives + True Negatives)
precision <- confusion_matrix[2, 2] / sum(confusion_matrix[2, ])
recall <- confusion_matrix[2, 2] / sum(confusion_matrix[, 2])
grid[i,5] = precision
grid[i,6] = recall

# Adjust rates if they are 0 or 1
hit_rate <- ifelse(hit_rate == 1, 0.99, ifelse(hit_rate == 0, 0.01, hit_rate))
false_alarm_rate <- ifelse(false_alarm_rate == 1, 0.99, ifelse(false_alarm_rate == 0, 0.01, false_alarm_rate))

# Calculate d'
d_prime <- qnorm(hit_rate) - qnorm(false_alarm_rate)
#grid[i,4] = d_prime


}



```

```{r}
# Load the ggplot2 package
library(ggplot2)
library(akima)





# Create the heatmap
plot_grid(ggplot(grid, aes(x = Var1, y = Var2, fill = F1, z = F1)) +
  geom_tile() +
  geom_contour(color = "black") +  # Add contours
  scale_fill_gradient(low = "blue", high = "red") + # Adjust colors as needed
  labs( x = "Threshold Difference",
       y = "Threshold Slope",
       fill = "F1") +
  theme_minimal(),
  ggplot(grid, aes(x = Var1, y = Var2, fill = Kappa, z = Kappa)) +
  geom_tile() +
  geom_contour(color = "black") +  # Add contours
  scale_fill_gradient(low = "blue", high = "red") + # Adjust colors as needed
  labs(x = "Threshold Difference",
       y = "Threshold Slope",
       fill = "Kappa") +
  theme_minimal(),
  ggplot(grid, aes(x = Var1, y = Var2, fill = sensitivity, z = sensitivity)) +
  geom_tile() +
  geom_contour(color = "black") +  # Add contours
  scale_fill_gradient(low = "blue", high = "red") + # Adjust colors as needed
  labs(x = "Threshold Difference",
       y = "Threshold Slope",
       fill = "Sens ") +
  theme_minimal(),
  ggplot(grid, aes(x = Var1, y = Var2, fill = Specificity, z = Specificity)) +
  geom_tile() +
  geom_contour(color = "black") +  # Add contours
  scale_fill_gradient(low = "blue", high = "red") + # Adjust colors as needed
  labs(x = "Threshold Difference",
       y = "Threshold Slope",
       fill = "Spec ") +
  theme_minimal())
  


#mean(grid$FA)  
```

Compare prophet to simple regression


```{r}


library(prophet)
# Fit the model
m <- prophet(Hotel_Reviews %>% mutate(ds = date_object, y =Reviewer_Score, cap=10, floor= 0) %>% filter(date_object < booking_time),changepoint.prior.scale = 0.0005,yearly.seasonality=TRUE,growth='logistic')

# Make future dataframe for predictions
future <- make_future_dataframe(m, periods = trip_time) # Predict for the next 30 days

# Forecast
forecast <- predict(m, train_data %>% mutate(ds = date_object, cap=10, floor= 0)  )
train_data$yhat = forecast$yhat
train_data$Score_cleaned = train_data$Reviewer_Score - train_data$yhat
#prophet_plot_components(m, forecast)

#plot(m, forecast)


fit_cleaned = lm(
   Score_cleaned ~ 0 +  Hotel_Name + time_ref:Hotel_Name, data = train_data)
#save(fit, file = "Simple_lm.RData")
all_coefficients = coef(fit_cleaned)
model_summary <- summary(fit_cleaned)




# Extract the coefficients table
coefficients_table <- model_summary$coefficients

# Extract only the interaction terms
interaction_summary <- coefficients_table[grep(":", rownames(coefficients_table)), ]


 time_effct_cleaned = data.frame(interaction_summary) %>% mutate(Name= rownames(.),
                                                         Name = stringr::str_replace(Name, c("Hotel_Name"),""),
                                                         Name = stringr::str_replace(Name, c(":time_ref"),"")) %>%
   arrange(Estimate) %>%
  mutate(Name = factor(Name, levels = Name)) %>% mutate(Pos = ifelse(t.value>t_threshold_slope, 1, 0),
                                                        Neg = ifelse(t.value<(-t_threshold_slope), 1, 0),
                                                        tendency = Pos-Neg) 

 
 time_effct_cleaned %>% ggplot(aes(x=Name, y= Estimate, colour = as.factor(tendency))) + 
   geom_point() +
   geom_pointrange(aes(ymin = Estimate - (Std..Error*2) ,ymax= Estimate + (Std..Error*2)),alpha=0.2) + 
   coord_flip() +
   geom_hline(yintercept = 0) + theme(legend.position = "None") +
   scale_color_manual(values=c("#F8766D", "#56B4E9", "#7CAE00")) + 
  annotate("text", x = Inf, y = Inf, label = paste("Positive trend:", round(mean(time_effct$Pos), 2)), hjust = 1, vjust = 2+3, size = 4, color = "#7CAE00") +
  annotate("text", x = Inf, y = Inf, label = paste("No clear trend:", round(mean(time_effct$tendency==0), 2)), hjust = 1, vjust = 3.5+3, size = 4, color = "#56B4E9") +
  annotate("text", x = Inf, y = Inf, label = paste("Negative trend:", round(mean(time_effct$Neg), 2)), hjust = 1, vjust = 5+3, size = 4, color = "#F8766D") + ylim(-1,1.1)
 
```







```{r}




both = merge(time_effct_cleaned, time_effct2 %>% select(Neg_label,Pos_label,tendency_label,Name, Estimate ), by ="Name")
m_my_data = my_data %>% group_by(Hotel_Name, group) %>% summarise(m = mean(Reviewer_Score)) %>% group_by(Hotel_Name) %>% summarise(dif = m[group == "after"] - m[group=="before"]) %>% mutate(Name = Hotel_Name)

both = merge(both, m_my_data %>% select(Name,dif ), by ="Name") %>% filter(abs(Estimate.x)<0.5,abs(Estimate.y)<0.5)

confusionMatrix_h <- confusionMatrix(as.factor(rbinom(length(both$Name),1,mean(both$Pos_label))), as.factor(both$Pos_label))
predicted = as.factor(both$Pos)
actual =  as.factor(both$Pos_label)

confusionMatrix <- confusionMatrix(predicted,actual, positive = "1")
f1_score <- confusionMatrix$byClass["F1"]


print(paste0("Correlation: ",cor(both$Estimate.x,both$Estimate.y)))
print(paste0("F1: ",f1_score))
print(paste0("Kappa: ",confusionMatrix$overall["Kappa"]))
print(paste0("Sensitivity: ", confusionMatrix$byClass["Sensitivity"]))
print(paste0("Specificity: ", confusionMatrix$byClass["Specificity"]))
print(paste0("D': ",calc_dprime(predicted,actual)))
#print(paste0("D' H0: ",calc_dprime(as.factor(rbinom(length(both$Name),1,mean(both$Pos_label))),actual)))
print(paste0("RD: ",mean(both$Pos_label[both$Pos==1])/mean(both$Pos_label)))
      



```


```{r}


threshold_slope = seq(0.7,0.99,0.02)
threshold_dif = seq(0.6,0.99,0.02)
grid = expand.grid(threshold_dif,threshold_slope, F1 = NA, Kappa =  NA, sensitivity = NA, Specificity=NA)

for (i in 1:length(grid[,1])){

  time_effct2 = trans_dif(grid[i,1])
  time_effct = trans_slope(grid[i,2],fit_cleaned)
  
time_effct2$Neg_label=time_effct2$Neg
time_effct2$Pos_label=time_effct2$Pos
time_effct2$tendency_label=time_effct2$tendency
both2 = merge(time_effct, time_effct2 %>% select(Neg_label,Pos_label,tendency_label,Name, Estimate ), by ="Name")
#grid[i,3] = mean(mean(both$Pos == 1 & both$Pos_label==1)) 
#grid[i,4] = mean(mean(both$Pos==0 & both$Pos_label == 1)) 


confusionMatrix <- confusionMatrix(as.factor(both2$Neg), as.factor(both2$Neg_label), positive = "1")
f1_score <- confusionMatrix$byClass["F1"]
grid[i,3] = f1_score
grid[i,4] = confusionMatrix$overall["Kappa"]
grid[i,5] = confusionMatrix$byClass["Sensitivity"]
grid[i,6] = confusionMatrix$byClass["Specificity"]
confusion_matrix <- table(Predicted = as.factor(both2$Neg), Actual = as.factor(both2$Neg_label))
hit_rate <- confusion_matrix[2, 2] / sum(confusion_matrix[, 2])  # True Positives / (True Positives + False Negatives)
false_alarm_rate <- confusion_matrix[2, 1] / sum(confusion_matrix[, 1])  # False Positives / (False Positives + True Negatives)


# Adjust rates if they are 0 or 1
hit_rate <- ifelse(hit_rate == 1, 0.99, ifelse(hit_rate == 0, 0.01, hit_rate))
false_alarm_rate <- ifelse(false_alarm_rate == 1, 0.99, ifelse(false_alarm_rate == 0, 0.01, false_alarm_rate))

# Calculate d'
d_prime <- qnorm(hit_rate) - qnorm(false_alarm_rate)
#grid[i,4] = d_prime

#grid[i,5] = mean(both2$Pos_label[both2$Pos==1])/mean(both2$Pos_label)
#grid[i,6] = mean(both2$Pos_label[both2$Pos==1])/mean(both2$Pos_label[both2$Pos==0])

rand = rbinom(length(both2$Pos_label),1, prob= mean(both2$Pos_label))
dummy= calc_dprime(rand,both2$Pos_label)#mean(both2$Pos_label[rand==1])/mean(both2$Pos_label[rand==0])
rand2 = rbinom(length(both2$Pos_label),1, prob= mean(both2$Pos_label))
dummy2= calc_dprime(rand2,both2$Pos_label)#mean(both2$Pos_label[rand==1])/mean(both2$Pos_label[rand==0])
rand3 = rbinom(length(both2$Pos_label),1, prob= mean(both2$Pos_label))
dummy3= calc_dprime(rand3,both2$Pos_label)#mean(both2$Pos_label[rand==1])/mean(both2$Pos_label[rand==0])
#grid[i,7] = mean(c(dummy,dummy2,dummy3))

}



```

```{r}
# Load the ggplot2 package
library(ggplot2)
library(akima)




# Create the heatmap
plot_grid(ggplot(grid, aes(x = Var1, y = Var2, fill = F1, z = F1)) +
  geom_tile() +
  geom_contour(color = "black") +  # Add contours
  scale_fill_gradient(low = "blue", high = "red") + # Adjust colors as needed
  labs( x = "Threshold Difference",
       y = "Threshold Slope",
       fill = "F1") +
  theme_minimal(),
  ggplot(grid, aes(x = Var1, y = Var2, fill = Kappa, z = Kappa)) +
  geom_tile() +
  geom_contour(color = "black") +  # Add contours
  scale_fill_gradient(low = "blue", high = "red") + # Adjust colors as needed
  labs(x = "Threshold Difference",
       y = "Threshold Slope",
       fill = "Kappa") +
  theme_minimal(),
  ggplot(grid, aes(x = Var1, y = Var2, fill = sensitivity, z = sensitivity)) +
  geom_tile() +
  geom_contour(color = "black") +  # Add contours
  scale_fill_gradient(low = "blue", high = "red") + # Adjust colors as needed
  labs(x = "Threshold Difference",
       y = "Threshold Slope",
       fill = "Sens ") +
  theme_minimal(),
  ggplot(grid, aes(x = Var1, y = Var2, fill = Specificity, z = Specificity)) +
  geom_tile() +
  geom_contour(color = "black") +  # Add contours
  scale_fill_gradient(low = "blue", high = "red") + # Adjust colors as needed
  labs(x = "Threshold Difference",
       y = "Threshold Slope",
       fill = "Spec ") +
  theme_minimal())
  


```









